CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `vw_team_match_action_pivot` AS
    SELECT 
        `tma`.`team_match_id` AS `team_match_id`,
        `tma`.`match_number` AS `match_number`,
        `tma`.`team_id` AS `team_id`,
        `tma`.`match_id` AS `match_id`,
        SUM(IF((`tma`.`action_name` = 'tele_high_scores'),
            `tma`.`quantity`,
            0)) AS `tele_high_score`,
        SUM(IF((`tma`.`action_name` = 'tele_low_dumps'),
            `tma`.`quantity`,
            0)) AS `tele_low_score`,
        SUM(IF((`tma`.`action_name` = 'tele_high_scores'),
            (`tma`.`quantity` * `tma`.`points`),
            0)) AS `tele_high_score_points`,
        SUM(IF((`tma`.`action_name` = 'tele_low_dumps'),
            (`tma`.`quantity` * `tma`.`points`),
            0)) AS `tele_low_score_points`,
        SUM(IF((`tma`.`action_name` = 'tele_fuel_bin_triggered'),
            `tma`.`quantity`,
            0)) AS `tele_fuel_bin_triggered`,
        SUM(IF((`tma`.`action_name` = 'tele_gear_delivered'),
            `tma`.`quantity`,
            0)) AS `tele_gear_delivered`,
        SUM(IF((`tma`.`action_name` = 'tele_loading_station_trip'),
            `tma`.`quantity`,
            0)) AS `tele_loading_station_trip`,
        SUM(IF((`tma`.`action_name` = 'tele_try_climb'),
            `tma`.`quantity`,
            0)) AS `tele_try_climb_flag`,
        SUM(IF((`tma`.`action_name` = 'tele_did_climb'),
            `tma`.`quantity`,
            0)) AS `tele_did_climb_flag`,
        SUM(IF((`tma`.`action_name` = 'tele_triggered_pressure_pad'),
            `tma`.`quantity`,
            0)) AS `tele_triggered_pressure_pad`,
        SUM(IF((`tma`.`action_name` = 'tele_triggered_pressure_pad'),
            `tma`.`object_count`,
            0)) AS `tele_climb_time_seconds`,
        SUM(IF((`tma`.`action_name` = 'auto_baseline_crossed'),
            `tma`.`quantity`,
            0)) AS `auto_baseline_crossed`,
        SUM(IF((`tma`.`action_name` = 'auto_low_dump'),
            `tma`.`quantity`,
            0)) AS `auto_low_dump`,
        SUM(IF((`tma`.`action_name` = 'auto_high_scores'),
            `tma`.`quantity`,
            0)) AS `auto_high_scores`,
        SUM(IF((`tma`.`action_name` = 'auto_high_scores'),
            (`tma`.`quantity` * `tma`.`points`),
            0)) AS `auto_high_score_points`,
        SUM(IF((`tma`.`action_name` = 'auto_high_missed'),
            `tma`.`quantity`,
            0)) AS `auto_high_missed`,
        SUM(IF((`tma`.`action_name` = 'auto_gear_delivered'),
            `tma`.`quantity`,
            0)) AS `auto_gear_delivered`,
        SUM(IF((`tma`.`action_name` = 'auto_fuel_bin_triggered'),
            `tma`.`quantity`,
            0)) AS `auto_fuel_bin_triggered`,
        SUM(IF((`tma`.`action_name` = 'tele_played_defensively'),
            `tma`.`quantity`,
            0)) AS `tele_played_defensively`,
        SUM(IF((`tma`.`action_name` = 'breakdown'),
            `tma`.`quantity`,
            0)) AS `breakdown`,
        SUM(IF((`tma`.`action_name` = 'disconnect'),
            `tma`.`quantity`,
            0)) AS `disconnect`,
        SUM(IF((`tma`.`action_name` = 'tele_high_missed'),
            `tma`.`quantity`,
            0)) AS `tele_high_missed`
    FROM
        `vw_team_match_action` `tma`
    GROUP BY `tma`.`team_match_id`